[package]
name = "natty-clicker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.19"
x11 = "2.21.0"
xcb = { version = "1.2.1", features = ["xinput", "xtest"] }
